### ISSUE TITLE
Start the movies API server in port 3001 to allow people to run both

### ISSUE THREAD

**Issue by dflock** [hootlex/the-majesty-of-vuejs-2#16]
This is a simple change and would:

- Allow people to easily run both the stories & movies API servers at the same time
- Avoid having to explain about shutting down the stories server before you start the movies one. You currently need to do this - and the book doesn't mention this, you just get an error about ports being in use.

**Comment by hootlex** [comment]
Do you need to have both `movies` and `stories` running?

**Comment by dflock** [comment]
No, not really - but in that case, you should probably explain to people to shut the `stories` one down before starting the `movies` one - otherwise they'll get an error. Moving the port would mean that you don't have to do that - and as a bonus,, removes the port clash and allows them both to run.

Obviously, it's up to you, it's your book - and it depends on what level of knowledge you're assuming in your reader. I've been building websites for ~20 yrs, so this was obvious to me, but might not be to everyone; just seemed like moving the port would remove a little bit of unnecessary friction.

**Comment by hootlex** [comment]
I agree, it might not be obvious to everyone.
I believe the best _fix_ is to add a notice, clarifying that you can't have both servers running on the same port.

Changing the port in the script will cause more confusion since people who are already working with the examples have to migrate their apps and also the texts/screenshots of the book have to be updated.

Thanks for your help.

**Comment by dflock** [comment]
Sure, fair enough.
